// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp-6I41OyrK75U4j1I-bYAzVdaYM_rZFE',
    appId: '1:680424401701:web:16f8865b9a9735bf1bc8cc',
    messagingSenderId: '680424401701',
    projectId: 'pish-3d992',
    authDomain: 'pish-3d992.firebaseapp.com',
    databaseURL: 'https://pish-3d992-default-rtdb.firebaseio.com',
    storageBucket: 'pish-3d992.appspot.com',
    measurementId: 'G-QE93HW234B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBSt0ncCRYsJ4Zcs-iKHKTmemmGM-58f4',
    appId: '1:680424401701:android:bb7f19af3c8b10751bc8cc',
    messagingSenderId: '680424401701',
    projectId: 'pish-3d992',
    databaseURL: 'https://pish-3d992-default-rtdb.firebaseio.com',
    storageBucket: 'pish-3d992.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOFpuf5b_ExoT6niOjzuEZjoJZ63ZxjAo',
    appId: '1:680424401701:ios:c4b8065d0ad963511bc8cc',
    messagingSenderId: '680424401701',
    projectId: 'pish-3d992',
    databaseURL: 'https://pish-3d992-default-rtdb.firebaseio.com',
    storageBucket: 'pish-3d992.appspot.com',
    iosBundleId: 'com.example.pishFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOFpuf5b_ExoT6niOjzuEZjoJZ63ZxjAo',
    appId: '1:680424401701:ios:6e9084f20ca805831bc8cc',
    messagingSenderId: '680424401701',
    projectId: 'pish-3d992',
    databaseURL: 'https://pish-3d992-default-rtdb.firebaseio.com',
    storageBucket: 'pish-3d992.appspot.com',
    iosBundleId: 'com.example.pishFlutter.RunnerTests',
  );
}
